[application]
name = "always-blue"
default_platform = "web"

[web.app]
title = "Always Blue - 技术博客"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[bundle]
identifier = "com.alwaysblue.app"
publisher = "TsaoLun"
copyright = "Copyright (c) TsaoLun 2024. All rights reserved."
category = "DeveloperTool"
short_description = "Always Blue - 技术博客"
long_description = "一个使用 Dioxus 和 Rust 构建的现代化技术博客应用，支持多语言和移动端。"

[bundle.ios]
development_team = "YOUR_TEAM_ID"  # 需要替换为你的开发团队ID
minimum_version = "11.0"
