/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const get_version: () => [number, number];
export const start_app: () => void;
export const test_add: (a: number, b: number) => number;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h0dd435c91e154c79: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h463f254b885f507b: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1ca02b268b625319: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h01961116222b65d7: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7b593d8c21c62f58: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1f3a4c9f5a5f2f89: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1f3a4c9f5a5f2f89_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1f3a4c9f5a5f2f89_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1f3a4c9f5a5f2f89_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1f3a4c9f5a5f2f89_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13e0f1f1a9abaff2_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h85ee971faa2ecb3f: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
